### ISSUE TITLE
Remove references to the TODO type

### ISSUE THREAD

**Issue by ghost** [BiancoRoyal/node-red-contrib-iiot-opcua#138]
### Description

The `Todo` type is intended as a temporary placeholder, but is very widely used across files, which helped get the TypeScript upgrade running quickly, but because `Todo` is simply an alias of the default `any` type, a lot of type information is lost by using it, which decreases the advantages of TypeScript over JavaScript. The Todo type should be completely removed and replaced by types that properly describe the objects that are assigned that type.

This Issue serves as an overview of the task's overall status. 

#### Good first issue
This issue has been marked as a "Good first issue", since removing the Todo type has a low risk of causing any breaking changes, while offering a great opportunity to navigate the code and become acquainted with the functionality and structure of a Node-RED node, node-opcua, and this project. 

### Successful removal
The Todo type is successfully removed when the import can be removed from a file, the build runs successfully via `gulp build` and the test completion remains the same (or better), run via `npm run summary`. 

### Contibuting
To contribute toward this issue, please first [create a separate issue](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/issues/new) including details of which files you are removing the `Todo` type from. 

### Remaining Files:
This is a list of all files that include use of the `Todo` type. A checked box implies that the Todo type has been removed.

- [ ] opcua-iiot-read.ts
- [ ] opcua-iiot-server.ts
- [ ] opcua-iiot-server-aso.ts
- [ ] opcua-iiot-write.ts
- [ ] opcua-iiot-method-caller.ts
- [ ] opcua-iiot-discovery.ts
- [ ] opcua-iiot-event.ts
- [ ] opcua-iiot-crawler.ts
- [ ] opcua-iiot-flex-server.ts
- [ ] opcua-iiot-response.ts
- [ ] opcua-iiot-inject.ts
- [ ] opcua-iiot-flex-connector.ts
- [ ] opcua-iiot-node.ts
- [ ] opcua-iiot-result-filter.ts
- [x] opcua-iiot-browser.ts
- [ ] opcua-iiot-listener.ts
- [ ] opcua-iiot-connector.ts
- [ ] opcua-iiot-server-cmd.ts
- [ ] types/helpers.ts
- [ ] core/opcua-iiot-core-listener.ts
- [ ] core/opcua-iiot-core-browser.ts
- [ ] core/opcua-iiot-core-inject.ts
- [ ] core/opcua-iiot-core-client.ts
- [ ] core/opcua-iiot-core-filter.ts
- [ ] core/opcua-iiot-core-method.ts
- [ ] core/opcua-iiot-core-server.ts
- [ ] core/opcua-iiot-core-response.ts
- [ ] core/opcua-iiot-core-connector.ts
- [ ] core/opcua-iiot-core.ts
- [ ] core/opcua-iiot-core-discovery.ts

**Comment by biancode** [comment]
We should use the node-opcua types here to minimize the own definitions.
