### ISSUE TITLE
TODO - update and new examples to import from the deployed package

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#141]
# Server
- [ ] server
- [ ] demo server
- [ ] flex-server
- [ ] secured server with user logins
- [ ] server with own types
- [ ] ASO server

# Client
- [ ] client read
- [ ] client write
- [ ] secured client with user login
- [ ] client flex connector
- [ ] listener and monitoring
- [ ] events and alarms
- [ ] browser
- [ ] crawler
- [ ] simple method call
- [ ] complex method call

# Response Tools
- [ ] response
- [ ] result filter

# Discovery
- [ ] local

# Demos
- [ ] all in one demo

**Comment by biancode** [comment]
# Existing Examples

## All in one

- [ ] all-in-one.json

## Client

- [ ] aso-browse-crawle.json
- [ ] browser-listen-group.json
- [ ] browser-read.json
- [ ] browser-to-listener.json
- [ ] browser.json
- [ ] crawler.json
- [ ] event-listener.json
- [ ] flex-connector-jwt.json
- [ ] flex-connector.json
- [ ] grouped-listener.json
- [ ] listener.json
- [ ] method-call.json
- [ ] read-history.json
- [ ] read-structure.json
- [ ] read-write.json
- [ ] read.json
- [ ] response.json
- [ ] result-filter.json
- [ ] write-read.json
- [ ] write.json


## External

- [ ] codesys-pi-sl.json
- [ ] prosys-simulator.json
- [ ] ua-cpp-demo-server.json

## Server

- [ ] program-server-with-context.json
- [ ] programmable-server.json
- [ ] server-ISA95.json
- [ ] server-aso-types.json
- [ ] server-demo-users.json
- [ ] server-demo.json

**Comment by biancode** [comment]
fixed soon from v4.1.x if we find time to work on it
