### ISSUE TITLE
[Test] e2e for browse node

### ISSUE THREAD

**Issue by dtq-one** [BiancoRoyal/node-red-contrib-iiot-opcua#163]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Browse` Node.

- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-browser-e2e.test.js
- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-browser-recursive-e2e.test.js

## Tasks

- [ ] Ensure examples for Browse Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] regular browser
    - [ ] browse to crawl
    - [ ] browse to read
    - [ ] browse to listener
    - [ ] browse to listener group
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
  - [ ] regular browser
  - [ ] browse to crawl
  - [ ] browse to read
  - [ ] browse to listener
  - [ ] browse to listener group

**Comment by biancode** [comment]
e2e tests working again

**Comment by biancode** [comment]
all fixed soon from v4.1.x if we find time to work on it
