### ISSUE TITLE
[Fix] Node-RED example for browse node

### ISSUE THREAD

**Issue by dtq-one** [BiancoRoyal/node-red-contrib-iiot-opcua#165]
## Background

In order to help with learning of adoption of Node-RED Contrib IIoT OPC-UA we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
  - [ ] regular browser
  - [ ] browse to crawl
  - [ ] browse to read
  - [ ] browse to listener
  - [ ] browse to listener group
- [ ] Ensure examples are working
  - [ ] regular browser
  - [ ] browse to crawl
  - [ ] browse to read
  - [ ] browse to listener
  - [ ] browse to listener group
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Browse Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.
