### ISSUE TITLE
[Test] e2e for Read Node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#166]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Read` Node.

- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-read-e2e.test.js

## Tasks

- [ ] Ensure examples for Read Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] regular read
    - [ ] read with response
    - [ ] read with filter
    - [ ] read from demo server
    - [ ] read from flex server
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
  - [ ] regular read
  - [ ] read with response
  - [ ] read with filter
  - [ ] read from demo server
  - [ ] read from flex server

**Comment by biancode** [comment]
from v4.0.5 the tests working again
