### ISSUE TITLE
[Fix] Node-RED example for Read node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#167]
## Background

In order to help with learning of adoption of Node-RED contribution package OPC-UA for IIoT, 
we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
  - [ ] regular read
  - [ ] read with response
  - [ ] read with filter
  - [ ] read from demo server
  - [ ] read from flex server
  - [ ] read from browse
- [ ] Ensure examples are working
  - [ ] regular read
  - [ ] read with response
  - [ ] read with filter
  - [ ] read from demo server
  - [ ] read from flex server
  - [ ] read from browse
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Read Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.

**Comment by biancode** [comment]
fixed soon from v4.1.x if we find time to work on it
