### ISSUE TITLE
[Test] e2e for Inject Node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#168]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Inject` Node.

## Tasks

- [ ] Ensure examples for Inject Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] read
    - [ ] write
    - [ ] browse
    - [ ] listen (monitoring)
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
    - [ ] read
    - [ ] write
    - [ ] browse
    - [ ] listen (monitoring)
