### ISSUE TITLE
[Fix] Node-RED examples with Inject node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#169]
## Background

In order to help with learning of adoption of Node-RED contribution package OPC-UA for IIoT, 
we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
    - [ ] read
    - [ ] write
    - [ ] browse
    - [ ] listen (monitoring)
- [ ] Ensure examples are working
    - [ ] read
    - [ ] write
    - [ ] browse
    - [ ] listen (monitoring)
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Inject Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.

**Comment by biancode** [comment]
timer is broken since v4.0+ to inject once - fixed soon from v4.1.x if we find time to work on it
