### ISSUE TITLE
[Test] e2e for Write Node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#177]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Write` Node.

- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-write-e2e.test.js

## Tasks

- [ ] Ensure examples for Write Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] regular write
    - [ ] write with response
    - [ ] write to demo server
    - [ ] write to flex server
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
  - [ ] regular write
  - [ ] write with response
  - [ ] write to demo server
  - [ ] write to flex server

**Comment by biancode** [comment]
Write Node is broken in e2e tests
