### ISSUE TITLE
[Fix] Node-RED example for Write node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#178]
## Background

In order to help with learning of adoption of Node-RED contribution package OPC-UA for IIoT, 
we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
  - [ ] regular write
  - [ ] write with response
  - [ ] write to demo server
  - [ ] write to flex server
  - [ ] write from browse
- [ ] Ensure examples are working
  - [ ] regular write
  - [ ] write with response
  - [ ] write to demo server
  - [ ] write to flex server
  - [ ] write from browse
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Write Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.

**Comment by biancode** [comment]
fixed soon from v4.1.x if we find time to work on it
