### ISSUE TITLE
[Test] e2e for Crawler node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#179]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Crawler` Node.

- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-crawler-e2e.test.js

## Tasks

- [ ] Ensure examples for Crawler Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] regular crawl
    - [ ] browse to crawl
    - [ ] crawler to read
    - [ ] crawler to listener
    - [ ] crawler to listener group
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
  - [ ] regular crawl
  - [ ] browse to crawl
  - [ ] crawler to read
  - [ ] crawler to listener
  - [ ] crawler to listener group
