### ISSUE TITLE
[Fix] Node-RED example for Crawler node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#180]
## Background

In order to help with learning of adoption of Node-RED Contrib IIoT OPC-UA we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
  - [ ] regular crawl
  - [ ] browse to crawl
  - [ ] crawler to read
  - [ ] crawler to listener
  - [ ] crawler to listener group
- [ ] Ensure examples are working
  - [ ] regular crawl
  - [ ] browse to crawl
  - [ ] crawler to read
  - [ ] crawler to listener
  - [ ] crawler to listener group
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Browse Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.

**Comment by biancode** [comment]
does not work with v2.64.1 at the moment - fixed soon from v4.1.x if we find time to work on it
