### ISSUE TITLE
[Test] e2e for Method-Caller node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#181]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Method-Caller` Node.

- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-method-caller-e2e.test.js

## Tasks

- [ ] Ensure examples for Method-Caller Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] regular method-call
    - [ ] complex method-caller
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
  - [ ] regular method-caller
  - [ ] complex method-caller

**Comment by biancode** [comment]
Method-Caller is broken on e2e test
