### ISSUE TITLE
[Fix] Node-RED example for Method-Caller node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#182]
## Background

In order to help with learning of adoption of Node-RED Contrib IIoT OPC-UA we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
  - [ ] regular method-call
  - [ ] complex method-call
- [ ] Ensure examples are working
  - [ ] regular method-call
  - [ ] complex method-call
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Method-Caller Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.

**Comment by biancode** [comment]
fixed soon from v4.1.x if we find time to work on it

**Comment by biancode** [comment]
fixed soon from v4.1.x if we find time to work on it
