### ISSUE TITLE
[Test] e2e for Connector node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#184]
## Background

Reliable e2e tests will help to ensure robustness and reliability for `Connector` Node.

- https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/test/e2e/opcua-iiot-connector-e2e.test.js

## Tasks

- [ ] Ensure examples for Connector Node works
  - [ ] import example(s) into workspace
  - [ ] manually test examples, particularly
    - [ ] regular connector
    - [ ] connector http API
- [ ] Fix test infrastructure: test are currently green, however actual nodes do not work/have bugs
  - [ ] determine root cause why test is green even though node is broken
  - [ ] possibly: test data in payload, not in msg, or vice versa
- [ ] create/ensure test cases are available and working for:
  - [ ] regular connector
  - [ ] connector http API
