### ISSUE TITLE
[Fix] Node-RED example for Connector node

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#185]
## Background

In order to help with learning of adoption of Node-RED Contrib IIoT OPC-UA we need to ensure examples are available for nodes and examples work reliably.

## Tasks

- [ ] Ensure examples are available
  - [ ] regular connector
  - [ ] connector http API
- [ ] Ensure examples are working
  - [ ] regular connector
  - [ ] connector http API
- [ ] Ensure Wiki entry is available (including screenshots?)
  - [ ] Explain how to get started with Connector Node and link to/explain example
  - [ ] additional training material, e.g. videos/youtube, etc.
